# Generated by Django 3.1.2 on 2023-01-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230107_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='negative',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='neutral',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='positive',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='url',
            field=models.CharField(default='URL', max_length=500),
        ),
    ]
